### ISSUE TITLE
The yaw angle is suddenly shifting to random values?

### ISSUE THREAD

**Issue by JeyP4** [wheaney/xrealAirLinuxDriver#7]
Hi

I am testing the xreal air glass.
I am observing a weird phenomenon, that when i play with just yaw and keep it still, suddenly it shift to random value. This is happening every-time. I attach a video also here. This is happening at every angle, not only at zero yaw.

https://github.com/wheaney/xrealAirLinuxDriver/assets/44414900/6b5091c6-d37d-44f3-bb17-89e43be54b80

I don't know if I have to write this issue to Fusion repository.

Do you observe the same?

- Jai

**Comment by wheaney** [comment]
Closing this with the issue linked above.
